services:
  - type: web
    name: flask-jwt-auth
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask_auth_db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true